// Kaynak: Solfeggio Frekansları (Frekans-Ozellikleri.pdf) + Çakralar (ÇAKRALAR.pdf)
// Titreşim felsefesi: 7 Hermetik Yasa — Titreşim Prensibi (Kybalion)

export const HERMETIK_ALINTILAR = [
  'Everende her şey sürekli olarak titreşir. Biz bu titreşimlere frekans deriz.',
  'Yaydığımız titreşimi istediğimiz konu ile aynı frekansa getirirsek güçlü bir köprü kurarız.',
  'Her şey titreşimdir. Frekansını yükselt, gerçekliğini dönüştür. — Kybalion',
]

export const SOLFEGGIO_SISTEMI = {
  aciklama: 'Guido d\'Arezzo\'nun 11. yüzyılda geliştirdiği ve Dr. Joseph Puleo\'nun 1970\'lerde elektromanyetik frekans araştırmalarıyla yeniden keşfettiği kadim ses sistemi.',
  kaynak: 'Gregorian ilahilerinden türetilmiş — Ut, Re, Mi, Fa, Sol, La, Si',
}

export const CHAKRA_FREQS = [
  {
    id: 'root',
    tr: 'Kök Çakrası',
    sanskrit: 'Muladhara',
    hz: 396,
    solfeggio: 'Ut / Do',
    mantra: 'LAM',
    renk: '#EF4444',
    gradyan: 'from-red-900/40 to-red-950/20',
    konum: 'Omurganın tabanı',
    element: 'Toprak',
    sifa: 'Korku ve suçluluk duygusuna direnç',
    etkiler: [
      'Bilinçaltındaki korku ve suçluluk kalıplarını çözer',
      'Maddi denge ve güvenlik hissi güçlenir',
      'Topraklanma, hayatta kalma içgüdüsü dengelenir',
      'Kaygı ve güvensizlik azalır',
    ],
    fiziksel: ['Ayak, bacak ve bel', 'Bağışıklık sistemi', 'Kemik yapısı'],
    meditasyonSuresi: 7,
    kaynakNotu: 'Solfeggio belgesi doğrulanmış',
  },
  {
    id: 'sacral',
    tr: 'Sakral Çakrası',
    sanskrit: 'Svadhisthana',
    hz: 417,
    solfeggio: 'Re',
    mantra: 'VAM',
    renk: '#F97316',
    gradyan: 'from-orange-900/40 to-orange-950/20',
    konum: 'Göbek altı',
    element: 'Su',
    sifa: 'Değişimi kabullenme ve uyumlanma',
    etkiler: [
      'Geçmişe takılı kalmadan anın koşullarına uyum sağlar',
      'Yaratıcılık ve duygusal akışkanlık açılır',
      'Sakral çakrayla birebir etkileşim halindedir',
      'Bağımlılık ve tatminsizlik kalıpları yumuşar',
    ],
    fiziksel: ['Üreme organları', 'Alt karın bölgesi', 'Böbrekler'],
    meditasyonSuresi: 7,
    kaynakNotu: 'Solfeggio belgesinde sakral çakra ile doğrudan eşleştirilmiş ✓',
  },
  {
    id: 'solar_plexus',
    tr: 'Güneş Pleksusu',
    sanskrit: 'Manipura',
    hz: 528,
    solfeggio: 'Mi',
    mantra: 'RAM',
    renk: '#EAB308',
    gradyan: 'from-yellow-900/40 to-yellow-950/20',
    konum: 'Mide bölgesi',
    element: 'Ateş',
    sifa: 'DNA onarımı · Sevgi frekansı · Yaratıcılık',
    ozel: true,
    ozelEtiket: '✦ Sevgi & DNA Frekansı',
    etkiler: [
      'Dr. Leonard Horowitz\'e göre varoluşun müzikal matematiği',
      'DNA yenilenmesine pozitif etki sağlar',
      'Hayal gücü ve yaratıcılık kapasitesini artırır',
      'Duyguları harekete geçiren en popüler Solfeggio frekansı',
    ],
    fiziksel: ['Mide ve sindirim', 'Karaciğer ve pankreas', 'Metabolizma'],
    meditasyonSuresi: 11,
    kaynakNotu: 'Solfeggio belgesinde DNA onarımı ve sevgi frekansı olarak tanımlanmış',
  },
  {
    id: 'heart',
    tr: 'Kalp Çakrası',
    sanskrit: 'Anahata',
    hz: 639,
    solfeggio: 'Fa',
    mantra: 'YAM',
    renk: '#22C55E',
    gradyan: 'from-green-900/40 to-green-950/20',
    konum: 'Göğüs ortası',
    element: 'Hava',
    sifa: 'Bağ kurma ve ilişkisel denge',
    etkiler: [
      'Pozitivite, empati ve tolerans gelişir',
      'Bireysel ve çevresel ilişkilere ahenk getirir',
      'Affetme kapasitesi ve koşulsuz sevgi açılır',
      'Kalp çakrasını etkileyen frekans olarak belgelenmiş',
    ],
    fiziksel: ['Kalp ve dolaşım', 'Akciğerler', 'Göğüs ve omuz bölgesi'],
    meditasyonSuresi: 7,
    kaynakNotu: 'Solfeggio belgesinde kalp çakrası ile doğrudan eşleştirilmiş ✓',
  },
  {
    id: 'throat',
    tr: 'Boğaz Çakrası',
    sanskrit: 'Vishuddha',
    hz: 741,
    solfeggio: 'Sol',
    mantra: 'HAM',
    renk: '#3B82F6',
    gradyan: 'from-blue-900/40 to-blue-950/20',
    konum: 'Boğaz bölgesi',
    element: 'Eter',
    sifa: 'İfade gücü ve çözüme ulaşma',
    etkiler: [
      'Kendini ifade etme ve analiz yeteneği güçlenir',
      'Hücrelerdeki elektromanyetik radyasyonu temizler',
      'Neden-sonuç ilişkisi kurma kapasitesi artar',
      'Söylenmemiş sözler ve bastırılmış ifadeler çözülür',
    ],
    fiziksel: ['Ses telleri ve boğaz', 'Tiroit bezi', 'Boyun ve çene'],
    meditasyonSuresi: 7,
    kaynakNotu: 'Solfeggio belgesi doğrulanmış',
  },
  {
    id: 'third_eye',
    tr: 'Üçüncü Göz',
    sanskrit: 'Ajna',
    hz: 852,
    solfeggio: 'La',
    mantra: 'AUM',
    renk: '#6366F1',
    gradyan: 'from-indigo-900/40 to-indigo-950/20',
    konum: 'Alın ortası',
    element: 'Işık',
    sifa: 'Kendine dönüş · Ruhsal farkındalık',
    etkiler: [
      'Farkındalığı artırır, gizli olanı açığa çıkarır',
      'Sakinleşme ve arındırma süreci başlar',
      'Ruhsal farkındalık ve içe dönme güçlenir',
      'Örüntüleri fark etme ve anlam katmanlarını okuma artar',
    ],
    fiziksel: ['Beyin ve sinir sistemi', 'Göz ve görme', 'Hipofiz bezi'],
    meditasyonSuresi: 11,
    kaynakNotu: 'Solfeggio belgesi: spirituel frekans. Mantra AUM — ÇAKRALAR.pdf (Mehmet Akdeniz) doğrulaması ✓',
  },
  {
    id: 'crown',
    tr: 'Taç Çakrası',
    sanskrit: 'Sahasrara',
    hz: 963,
    solfeggio: 'Si',
    mantra: 'SESSİZLİK',
    renk: '#A855F7',
    gradyan: 'from-purple-900/40 to-purple-950/20',
    konum: 'Başın tepesi',
    element: 'Kozmik Bilinç',
    sifa: 'Kozmik bağlantı · İlahi akış',
    etkiler: [
      'En yüksek Solfeggio frekansı — ilahi ile bağlantı',
      'Kozmik bilinç ve aşkınlık hali',
      'Pineal bez aktivasyonu',
      'Ruhsal açılım ve anlam arayışının doruk noktası',
    ],
    fiziksel: ['Pineal bez', 'Serebral korteks', 'Merkezi sinir sistemi'],
    meditasyonSuresi: 21,
    kaynakNotu: '⚠ 963 Hz Solfeggio belgesinde yok — geleneksel new-age ataması. Mantra SESSİZLİK — ÇAKRALAR.pdf (Mehmet Akdeniz) ✓',
  },
]

export const TAM_MEDITASYON = {
  toplamDakika: 21,
  aciklama: '7 çakra · her biri 3 dakika · tabandan taca yükselen enerji akışı',
  siralama: ['root', 'sacral', 'solar_plexus', 'heart', 'throat', 'third_eye', 'crown'],
  cakraBasiDakika: 3,
}
